### ISSUE TITLE
running apcupsd on proxmox host with the rest in a docker lxc: Telegraf error

### ISSUE THREAD

**Issue by lignicolos** [bnhf/apcupsd-admin-plus#2]
I'm running apcupsd on my Proxmox host.

Docker is running in an LXC on Proxmox. The docker stack is running apcupsd-cgi, Influxdb, Telegraf, and Grafana with apcupsd-cgi pointed at my proxmox host IP:port and pulling data properly.

Telegraf fails with the error below.
"2024-07-20T22:13:30Z E! [inputs.apcupsd] Error in plugin: dial tcp: address $UPS2: missing port in address"

I do not have UPS2 defined anywhere. I noticed the Telegraf.conf has multiple servers defined. I tried modifying this file but it is overwritten by the apcupsd-cgi everytime it starts.

servers = ["tcp://$UPS1", "tcp://$UPS2", "tcp://$UPS3", "tcp://$UPS4", "tcp://$UPS5", "tcp://$UPS6", "tcp://$UPS7", "tcp://$UPS8"]

apcupsd-cgi docker environment:
    environment:
      - UPSHOSTS=192.168.200.1:3551
      - UPSNAMES=proxmox
      - DASHBOARD_PROVISION=true
      - TZ=America/New_York

telegraf docker environment:
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - DOCKER_INFLUXDB_INIT_ORG=proxmox
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="<token>"
      - UPS1=192.168.200.1:3551

**Comment by bnhf** [comment]
@lignicolos 

I'm not using all of the UPS devices defined globally either, six out of eight in my case. Try leaving the Docker compose as-is, but delete any UPSx values in the Portainer-Stacks Environment variables section that don't have values. For example in my case I only have UPS1 to UPS6 defined:

![screenshot-raspberrypi4-2024 07 20-16_52_33](https://github.com/user-attachments/assets/70a779e6-19c8-4796-93e4-a6f36e471763)
