### ISSUE TITLE
Issue with PVE shutdown

### ISSUE THREAD

**Issue by vantech14** [bnhf/apcupsd-admin-plus#3]
Hi There, 

Hope you can help me. The APCUPSD works fine, and integrated with home assistant. I have it running on an Ubuntu host, running on Proxmox. I am trying to shut down the Proxmox OS as follows: 

      - PVE_SHUTDOWN_HOSTS=192.168.100.3 # Ordered list of pve hostnames (or IPs) to be used for API shutdown. Used with matching lists of $PVE_SHUTDOWN_NODES and $PVE_SHUTDOWN_TOKENS
      - 
      - PVE_SHUTDOWN_NODES=pve # Ordered list of pve nodes. Used with matching lists of $PVE_SHUTDOWN_HOSTS and $PVE_SHUTDOWN_TOKENS
      - 
      - PVE_SHUTDOWN_TOKENS=apcupsd@pve!apcupsd=bf79bae8-e061-4466-a6b5-xxxxxx # Ordered list of pve API tokens with secrets in the form <username>@<node>!<api_token>=<api_secret>`

I have also tried the full proxmox URL https://192.168.100.3:8006 and various other combinations. 

However i get this error message in the logs each time: 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 192.168.100.3
Failed to open connection to "system" message bus: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)

Any ideas? The Ubuntu host OS can ping this IP successfully. 

Thanks.

**Comment by bnhf** [comment]
@vantech14 

Did you give your "apcupsd" user the necessary permissions to initiate a shutdown?

My user is called "shutdown" and has these permissions:

![screencapture-file-C-Users-slayer-Downloads-screenshot-pve-8006-2024-07-22-13-10-19-png-2024-07-22-13_10_52-edit](https://github.com/user-attachments/assets/3d8a0c93-b707-451e-94f6-bb1cee6d1569)

**Comment by vantech14** [comment]
> @vantech14
> 
> Did you give your "apcupsd" user the necessary permissions to initiate a shutdown?
> 
> My user is called "shutdown" and has these permissions:
> 
> ![screencapture-file-C-Users-slayer-Downloads-screenshot-pve-8006-2024-07-22-13-10-19-png-2024-07-22-13_10_52-edit](https://private-user-images.githubusercontent.com/41088895/351084901-3d8a0c93-b707-451e-94f6-bb1cee6d1569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzYxMzcsIm5iZiI6MTcyMTY3NTgzNywicGF0aCI6Ii80MTA4ODg5NS8zNTEwODQ5MDEtM2Q4YTBjOTMtYjcwNy00NTFlLTk0ZjYtYmIxY2VlNmQxNTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE5MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MTg3NzUzODk2Yzc3NWJjYzhkM2RhYjMzMjc3Y2NiOTQ4YzQ0YWU1OTg1N2IzZmM4MDllMjZlMDIxMzM0ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFBWR07IHQH1WXnGx4rkOVN-0hSZltaV1RiQPpci9N4)

@bnhf 

Here is my api setup:

![image](https://github.com/user-attachments/assets/fd8270b5-9a46-4314-9877-da43d846906e)

and 

![image](https://github.com/user-attachments/assets/6173f823-8937-4f2d-9916-5323df8fff85)


I cant see why this isnt working. I also tried to disable apparmor on the host to no avail? The user is setup as a proxmox PVE realm rather than a PAM but i dont think this should make a difference?

Thanks.

**Comment by bnhf** [comment]
@vantech14 

Have you tried executing the curl command to initiate a shutdown from another computer? Here's what it looks like in the script, and you can just sub-in your values in place of the env vars (everything inside and including the ${} for each HOSTS, NODES, and TOKENS):
```
curl "https://${HOSTS[$i]}:8006/api2/extjs/nodes/${NODES[$i]}/status" -H "Authorization: PVEAPIToken=${TOKENS[$i]}" -H "Content-Type: application/x-www-form-urlencoded" --data "command=shutdown" --insecure
```
If that doesn't work, I'd suggest going to the Proxmox forum, as whatever is going on is Proxmox related. I'm pretty sure there are one or two threads on the subject of API token shutdowns.

**Comment by vantech14** [comment]
> @vantech14 
> 
> 
> 
> Have you tried executing the curl command to initiate a shutdown from another computer? Here's what it looks like in the script, and you can just sub-in your values in place of the env vars (everything inside and including the ${} for each HOSTS, NODES, and TOKENS):
> 
> ```
> 
> curl "https://${HOSTS[$i]}:8006/api2/extjs/nodes/${NODES[$i]}/status" -H "Authorization: PVEAPIToken=${TOKENS[$i]}" -H "Content-Type: application/x-www-form-urlencoded" --data "command=shutdown" --insecure
> 
> ```
> 
> If that doesn't work, I'd suggest going to the Proxmox forum, as whatever is going on is Proxmox related. I'm pretty sure there are one or two threads on the subject of API token shutdowns.

@bnhf 

root@ubuntu-rpi:~# curl "https://192.168.100.3:8006/api2/extjs/nodes/pve/status" -H "Authorization: PVEAPIToken=apcupsd@pve!apcupsd=bf79bae8-e061-4466-a6b5-redacted" -H "Content-Type: application/x-www-form-urlencoded" --data "command=shutdown" --insecure
-bash: !apcupsd=bf79bae8: event not found

Suggests there is an issue with the format of the username? 

Command issued:

curl "https://192.168.100.3:8006/api2/extjs/nodes/pve/status" -H "Authorization: PVEAPIToken=apcupsd@pve!apcupsd=bf79bae8-e061-4466-a6b5-redacted" -H "Content-Type: application/x-www-form-urlencoded" --data "command=shutdown" --insecure

Hmm?

**Comment by bnhf** [comment]
@vantech14 

Try replacing the double quotes with single quotes for use on the command line.

**Comment by vantech14** [comment]
@bnhf i resolved. The issue was that the user needed the same permissions as the API token. I at first only setup access for the API token. 

![image](https://github.com/user-attachments/assets/e6cf52b8-4c42-47eb-a392-6acbc49a49fc)

`      - PVE_SHUTDOWN_HOSTS=192.168.100.3 # Ordered list of pve hostnames (or IPs) to be used for API shutdown. Used with matching lists of $PVE_SHUTDOWN_NODES and $PVE_SHUTDOWN_TOKENS
      - PVE_SHUTDOWN_NODES=pve # Ordered list of pve nodes. Used with matching lists of $PVE_SHUTDOWN_HOSTS and $PVE_SHUTDOWN_TOKENS
      - PVE_SHUTDOWN_TOKENS=shutdown@pam!shutdown=836fbe6b-2bfb-4888-a07d-redacted # Ordered list of pve API tokens with secrets in the form <username>@<node>!<api_token>=<api_secret>`

Thanks for your help!
